on: [push, pull_request]

jobs:
  slack_notify_success:
    runs-on: ubuntu-latest
    name: Test the action on success
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Success
        run: exit 0
      - name: Action
        uses: ./
        if: always()
        with:
          event: ${{ toJson(github.event) }}
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: pr
